theme: jekyll-theme-minimal
logo: https://github.com/ADeepTech/WAGO-PLC-Tutorials/blob/master/assets/images/wago-pfc-200.jpg?raw=true
title: WAGO PLC Tutorials
show_downloads: false
google_analytics: UA-165013852-4
